apiVersion: v1
baseDomain: tale.rhcee.support
compute:
- hyperthreading: Enabled
  name: worker
  platform: 
    aws:
      type: m4.large
      zones:
       - eu-west-1a
       - eu-west-1b
  replicas: 3
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: 
    aws:
      type: m4.xlarge
      zones:
       - eu-west-1a
       - eu-west-1b
  replicas: 3
metadata:
  creationTimestamp: null
  name: lolakrit
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineCIDR: 172.20.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: eu-west-1
    subnets:
      - subnet-0ef18f913785fd970
      - subnet-0d400363037e84064
publish: Internal
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3JobnN1cHBvcnRqamVyZXpybzFoaWRheDBvbHZ0enlkNmtidXNtc3psb2J3bjpUR1RYNTU0M1FEUk0xRU5BQjBVTk5aVEIyMjdLSjhHVEVJU1Q3Q1AwTjc5N1o1TFFKV1lNVFpVQ05OT0tIM0dO","email":"jjerezro@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K3JobnN1cHBvcnRqamVyZXpybzFoaWRheDBvbHZ0enlkNmtidXNtc3psb2J3bjpUR1RYNTU0M1FEUk0xRU5BQjBVTk5aVEIyMjdLSjhHVEVJU1Q3Q1AwTjc5N1o1TFFKV1lNVFpVQ05OT0tIM0dO","email":"jjerezro@redhat.com"},"registry.connect.redhat.com":{"auth":"NTIzMjU0MDB8dWhjLTFIaWRhWDBvbHZ0WnlkNmtidVNNc3psb0JXTjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJaamszTjJGbVpUY3lNMkkwTURjME9HSmlNakJoWmpWa05Ua3haRFkzWkNKOS5pZGx6YTNUc2swaWc1Ui1xQTNrTkVqUDFnemQ5MzBYOGlzOVVrMTZzWEdxVWVqNDVkamVDQ1ZJa2pDOGxhMFBKeWVIX2ZXRVNpRU5ESUhfUThBeHRlRkQyVXpQMmhsVEhaMFBKWjlJN0t5ZW5KNTdiYW00aWlQTE9NOWRaTmFuWTRKNnhkSXIyQ3duSm1QdTdhUnJ5REY0R0FPOGJWQjBvMlhpaXFyNXRULWE2UEkwVzNmR2lQT1NiOHduQzBZMUw1a25lZG9mT2JmNkFJeEVJZnVYNGoyRUs5QUluSUhnejlaS0hNZ1NmWmFicm05clg5YmxtS1pLMUFlcmw5RUpMSVVuaGZMNWpRcUZMZjBtRGwxOUFkQ05XMWJGSHlKeWJlaDl4T0xxcXVwd1hMa2s4R01nMkRNMjEzWFdTQlRLa0prRTZPRkRBR3VVMHk1QVNhN2xvYUJQUFRyUWNOZ28tUDR4Y2xXQXVZb195VEdaX3hZSkhfUFJOdWd1ZXdFZUdEaDdYX0F1RW9TV3RLeThnZ0dKcnlUOWpMWExCaWJFeEdUdUh4ZkU3U1RwNDJiSHlWM0J2dUE5ODdzaXdydnh0Nm10UDJRX3J1Mi1jRmR3RjE4bEpPYm9fWDFTdmNxa0F0QmhVTmM0elFpdEtJb3d3T0Ztbk9pOGtTVFhRTk50ZmY0T2xCTFFYLURoQklWSDlqQXVLY05jcU9nTUxrc1pjMkxqRjloRkJBYzBtbGx4WXJON2lQRDAwRlJFOVNmTTJIMDQ3Mkc4NDJEbFhDbkhYY0VBUHVpTlhmZ3R4OV9sY1AwZzdaejlhSDlRb0djM19GX2podW16M3hsSFVfOHdjSy11YUJwbHk4SEU3UjNvb24wZFhNeXNXTHdRYWt5aGpPejJWUEJGRlY5QQ==","email":"jjerezro@redhat.com"},"registry.redhat.io":{"auth":"NTIzMjU0MDB8dWhjLTFIaWRhWDBvbHZ0WnlkNmtidVNNc3psb0JXTjpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTJaamszTjJGbVpUY3lNMkkwTURjME9HSmlNakJoWmpWa05Ua3haRFkzWkNKOS5pZGx6YTNUc2swaWc1Ui1xQTNrTkVqUDFnemQ5MzBYOGlzOVVrMTZzWEdxVWVqNDVkamVDQ1ZJa2pDOGxhMFBKeWVIX2ZXRVNpRU5ESUhfUThBeHRlRkQyVXpQMmhsVEhaMFBKWjlJN0t5ZW5KNTdiYW00aWlQTE9NOWRaTmFuWTRKNnhkSXIyQ3duSm1QdTdhUnJ5REY0R0FPOGJWQjBvMlhpaXFyNXRULWE2UEkwVzNmR2lQT1NiOHduQzBZMUw1a25lZG9mT2JmNkFJeEVJZnVYNGoyRUs5QUluSUhnejlaS0hNZ1NmWmFicm05clg5YmxtS1pLMUFlcmw5RUpMSVVuaGZMNWpRcUZMZjBtRGwxOUFkQ05XMWJGSHlKeWJlaDl4T0xxcXVwd1hMa2s4R01nMkRNMjEzWFdTQlRLa0prRTZPRkRBR3VVMHk1QVNhN2xvYUJQUFRyUWNOZ28tUDR4Y2xXQXVZb195VEdaX3hZSkhfUFJOdWd1ZXdFZUdEaDdYX0F1RW9TV3RLeThnZ0dKcnlUOWpMWExCaWJFeEdUdUh4ZkU3U1RwNDJiSHlWM0J2dUE5ODdzaXdydnh0Nm10UDJRX3J1Mi1jRmR3RjE4bEpPYm9fWDFTdmNxa0F0QmhVTmM0elFpdEtJb3d3T0Ztbk9pOGtTVFhRTk50ZmY0T2xCTFFYLURoQklWSDlqQXVLY05jcU9nTUxrc1pjMkxqRjloRkJBYzBtbGx4WXJON2lQRDAwRlJFOVNmTTJIMDQ3Mkc4NDJEbFhDbkhYY0VBUHVpTlhmZ3R4OV9sY1AwZzdaejlhSDlRb0djM19GX2podW16M3hsSFVfOHdjSy11YUJwbHk4SEU3UjNvb24wZFhNeXNXTHdRYWt5aGpPejJWUEJGRlY5QQ==","email":"jjerezro@redhat.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7nGtL1aP9SDa7Vt+2DdysKZXRifET33IgV0Zy8QWzwWgnwUmOFi2fgXwl2TMUzOTg3TnCPCkQQSAIcRTEVt9WFz4v/rKDswqIYykEFkFDrDZZZ4n/FJuviJ/IZOi7e9X67FcW8+bydO2rzlABAr+JGgdD8Y6iaBAzRSfJh+MpEhm5P3SnCgsIk0H/fgtyV35kYyN7o4NM3bLBdF5fI8mUX5UYANWM+r4c8h/4f+LyRtdP/cbqyw5nX7Fy7FqoIkZVKIhN4ng/QxOnutlfwkGqizenqUtxQxd0npwsIbzhDDY/wJ3KagV271oVEoMLhqF9gJaUP5EtYw4dZ56+y0Zt jjerezro@jjerezro.remote.csb
